import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const rawQuotes = `
## January: Faith, Trust, & Reliance (Tawakkul)

   1. "And whoever relies upon Allah – then He is sufficient for him." (65:3)
   2. "Indeed, Allah loves those who rely [upon Him]." (3:159)
   3. "Say, 'Never will we be struck except by what Allah has decreed for us.'" (9:51)
   4. "He is our protector; and upon Allah let the believers rely." (9:51)
   5. "And rely upon the Ever-Living who does not die." (25:58)
   6. "And exalt [Allah] with His praise. And sufficient is He." (25:58)
   7. "Unquestionably, to Allah belongs whatever is in the heavens and earth." (10:55)
   8. "Is not Allah sufficient for His servant?" (39:36)
   9. "And they say, 'Sufficient for us is Allah, and [He is] the best disposer of affairs.'" (3:173)
   10. "And my success is not but through Allah." (11:88)
   11. "Upon Him I have relied, and to Him I return." (11:88)
   12. "And to Allah belongs the unseen of the heavens and the earth." (11:123)
   13. "So worship Him and rely upon Him." (11:123)
   14. "And your Lord is not unaware of that which you do." (11:123)
   15. "Say, 'He is the Most Merciful; we have believed in Him, and upon Him we have relied.'" (67:29)
   16. "Lord of the East and the West - there is no deity except Him, so take Him as Disposer of [your] affairs." (73:9)
   17. "And establish prayer and give zakah and obey the Messenger that you may receive mercy." (24:56)
   18. "And when you have decided, then rely upon Allah." (3:159)
   19. "If Allah should aid you, no one can overcome you." (3:160)
   20. "And if He should forsake you, who is there that can aid you after Him?" (3:160)
   21. "And upon Allah let the believers rely." (3:160)
   22. "And put your trust in Allah; and sufficient is Allah as Disposer of affairs." (33:3)
   23. "The believers are only those who, when Allah is mentioned, their hearts feel fear." (8:2)
   24. "And when His verses are recited to them, it increases them in faith." (8:2)
   25. "And upon their Lord they rely." (8:2)
   26. "Those who establish prayer and spend from what We have provided them." (8:3)
   27. "Those are the believers, truly." (8:4)
   28. "For them are degrees [of high position] with their Lord and forgiveness and noble provision." (8:4)
   29. "And Allah would not punish them while you are among them." (8:33)
   30. "And Allah would not punish them while they seek forgiveness." (8:33)
   31. "And do not weaken and do not grieve, and you will be superior if you are [true] believers." (3:139)

## February: Patience & Resilience (Sabr)

   1. "O you who have believed, seek help through patience and prayer." (2:153)
   2. "Indeed, Allah is with the patient." (2:153)
   3. "And We will surely test you with something of fear and hunger." (2:155)
   4. "And a loss of wealth and lives and fruits, but give good tidings to the patient." (2:155)
   5. "Who, when disaster strikes them, say, 'Indeed we belong to Allah, and indeed to Him we will return.'" (2:156)
   6. "Those are the ones upon whom are blessings from their Lord and mercy." (2:157)
   7. "And it is those who are the [rightly] guided." (2:157)
   8. "For indeed, with hardship will be ease." (94:5)
   9. "Indeed, with hardship will be ease." (94:6)
   10. "Allah does not burden a soul beyond that it can bear." (2:286)
   11. "And be patient, [O Muhammad], and your patience is not but through Allah." (16:127)
   12. "And do not grieve over them and do not be in distress." (16:127)
   13. "Indeed, Allah is with those who fear Him and those who are doers of good." (16:128)
   14. "So be patient. Indeed, the promise of Allah is truth." (30:60)
   15. "And let them not disquiet you who are not certain [in faith]." (30:60)
   16. "And be patient over what befalls you." (31:17)
   17. "Indeed, [all] that is of the matters [requiring] determination." (31:17)
   18. "Except those who are patient and do righteous deeds." (11:11)
   19. "Those will have forgiveness and great reward." (11:11)
   20. "And be patient, for indeed, Allah does not allow to be lost the reward of those who do good." (11:115)
   21. "Peace be upon you for what you patiently endured." (14:24)
   22. "And excellent is the final home." (14:24)
   23. "And We will surely give those who were patient their reward according to the best of what they used to do." (16:96)
   24. "Only those who are patient will be given their reward without account." (39:10)
   25. "So be patient with a beautiful patience." (70:5)
   26. "And endure patiently, for your Lord's sake." (74:7)
   27. "And We made from among them leaders guiding by Our command when they were patient." (32:24)
   28. "And they used to be certain of Our signs." (32:24)

## March: Mercy & Forgiveness (Rahmah & Maghfirah)

   1. "Say, 'O My servants who have transgressed against themselves...'" (39:53)
   2. "'...do not despair of the mercy of Allah.'" (39:53)
   3. "Indeed, Allah forgives all sins." (39:53)
   4. "Indeed, it is He who is the Forgiving, the Merciful." (39:53)
   5. "And My mercy encompasses all things." (7:156)
   6. "Your Lord has decreed upon Himself mercy." (6:54)
   7. "He who does a wrong out of ignorance and then repents after that and corrects himself..." (6:54)
   8. "...then indeed, He is Forgiving and Merciful." (6:54)
   9. "And ask forgiveness of your Lord and then repent to Him." (11:90)
   10. "Indeed, my Lord is Merciful and Affectionate." (11:90)
   11. "And whoever does a wrong or wrongs himself but then seeks forgiveness of Allah..." (4:110)
   12. "...will find Allah Forgiving and Merciful." (4:110)
   13. "Declare, [O Muhammad], to My servants that I am the Forgiving, the Merciful." (15:49)
   14. "And indeed, I am the Perpetual Forgiver of whoever repents and believes." (20:82)
   15. "And does righteous deeds and then continues in guidance." (20:82)
   16. "But your Lord is the Forgiving, full of mercy." (18:58)
   17. "The Lord of the heavens and the earth and whatever is between them, the Exalted in Might, the Perpetual Forgiver." (38:66)
   18. "He created the heavens and earth in truth." (39:5)
   19. "He wraps the night over the day and wraps the day over the night." (39:5)
   20. "And He has subjected the sun and the moon, each running [its course] for a specified term." (39:5)
   21. "Unquestionably, He is the Exalted in Might, the Perpetual Forgiver." (39:5)
   22. "And He is the One who accepts repentance from His servants." (42:25)
   23. "And He pardons misdeeds, and He knows what you do." (42:25)
   24. "He answers [the supplication of] those who have believed and done righteous deeds." (42:26)
   25. "And He increases them from His bounty." (42:26)
   26. "But the disbelievers will have a severe punishment." (42:26)
   27. "Our Lord, You have encompassed all things in mercy and knowledge." (40:7)
   28. "So forgive those who have repented and followed Your way." (40:7)
   29. "And protect them from the punishment of Hellfire." (40:7)
   30. "And hasten to forgiveness from your Lord and a garden as wide as the heavens and earth." (3:133)
   31. "Prepared for the righteous." (3:133)

## April: Inner Peace & Healing (Shifa)

   1. "Verily, in the remembrance of Allah do hearts find rest." (13:28)
   2. "Those who have believed and whose hearts are assured by the remembrance of Allah." (13:28)
   3. "O mankind, there has to you come instruction from your Lord and healing for what is in the breasts." (10:57)
   4. "And guidance and mercy for the believers." (10:57)
   5. "And We send down of the Quran that which is healing and mercy for the believers." (18:82)
   6. "And it does not increase the wrongdoers except in loss." (18:82)
   7. "And when I am ill, it is He who cures me." (26:80)
   8. "And He will ease the breasts of a believing people." (9:14)
   9. "And remove the anger of their hearts." (9:15)
   10. "And Allah turns in forgiveness to whom He wills; and Allah is Knowing and Wise." (9:15)
   11. "Say, 'It is for those who believe, a guidance and cure.'" (41:44)
   12. "There emerges from their bellies a drink, varying in colors, in which there is healing for people." (16:69)
   13. "Indeed in that is a sign for a people who give thought." (16:69)
   14. "Then He sent down His tranquility upon His Messenger and upon the believers." (9:26)
   15. "And sent down soldiers which you did not see." (9:26)
   16. "It is He who sent down tranquility into the hearts of the believers." (48:4)
   17. "That they would increase in faith along with their [present] faith." (48:4)
   18. "And to Allah belong the soldiers of the heavens and the earth." (48:4)
   19. "And Allah is Knowing and Wise." (48:4)
   20. "Allah is the ally of those who believe." (2:257)
   21. "He brings them out from darknesses into the light." (2:257)
   22. "And He found you lost and guided [you]." (93:7)
   23. "And He found you poor and made [you] self-sufficient." (93:8)
   24. "So comfort your heart, for your Lord has not forsaken you." (93:3)
   25. "And the Hereafter is better for you than the first [life]." (93:4)
   26. "And your Lord is going to give you, and you will be satisfied." (93:5)
   27. "Did He not find you an orphan and give [you] refuge?" (93:6)
   28. "Therefore, the orphan do not oppress." (93:9)
   29. "And as for the petitioner, do not repel [him]." (93:10)
   30. "And as for the favor of your Lord, report [it]." (93:11)

## May: Prayer & Supplication (Dua)

   1. "And when My servants ask you, [O Muhammad], concerning Me - indeed I am near." (2:186)
   2. "I respond to the invocation of the supplicant when he calls upon Me." (2:186)
   3. "So let them respond to Me [by obedience] and believe in Me that they may be [rightly] guided." (2:186)
   4. "And your Lord says, 'Call upon Me; I will respond to you.'" (40:60)
   5. "Call upon your Lord in humility and privately." (7:55)
   6. "Indeed, He does not like transgressors." (7:55)
   7. "And invoke Him in fear and aspiration." (7:56)
   8. "Indeed, the mercy of Allah is near to the doers of good." (7:56)
   9. "Is He [not best] who responds to the desperate one when he calls upon Him and removes evil?" (27:62)
   10. "And makes you inheritors of the earth? Is there a deity with Allah?" (27:62)
   11. "Little do you remember." (27:62)
   12. "So exalt the name of your Lord, the Most Great." (56:74)
   13. "Exalt the name of your Lord, the Most High." (87:1)
   14. "Our Lord, pour upon us patience and let us die as Muslims [in submission to You]." (7:126)
   15. "Our Lord, grant us from Yourself mercy and prepare for us from our affair right guidance." (18:10)
   16. "My Lord, expand for me my breast [with assurance]." (20:25)
   17. "And ease for me my task." (20:26)
   18. "And untie the knot from my tongue." (20:27)
   19. "That they may understand my speech." (20:28)
   20. "My Lord, increase me in knowledge." (20:114)
   21. "Indeed, adversity has touched me, and you are the Most Merciful of the merciful." (21:83)
   22. "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers." (21:87)
   23. "So We responded to him and delivered him from the distress." (21:88)
   24. "And thus do We save the believers." (21:88)
   25. "My Lord, do not leave me alone [with no heir], while you are the best of inheritors." (21:89)
   26. "Our Lord, forgive us and our brothers who preceded us in faith." (59:10)
   27. "And put not in our hearts any resentment toward those who have believed." (59:10)
   28. "Our Lord, indeed You are Kind and Merciful." (59:10)
   29. "Our Lord, upon You we have relied, and to You we have returned, and to You is the destination." (60:4)
   30. "Our Lord, perfect for us our light and forgive us." (66:8)
   31. "Indeed, You are over all things competent." (66:8)

## June: Gratitude & Blessings (Shukr)

   1. "And [remember] when your Lord proclaimed, 'If you are grateful, I will surely increase you.'" (14:7)
   2. "But if you deny, indeed, My punishment is severe." (14:7)
   3. "So remember Me; I will remember you." (2:152)
   4. "And be grateful to Me and do not deny Me." (2:152)
   5. "And if you should count the favors of Allah, you could not enumerate them." (16:18)
   6. "Indeed, Allah is Forgiving and Merciful." (16:18)
   7. "And whatever you have of favor - it is from Allah." (16:53)
   8. "Then when adversity touches you, to Him you cry for help." (16:53)
   9. "Then when He removes the adversity from you, at once a party of you associates others with their Lord." (16:54)
   10. "And He gave you from all you asked of Him." (14:34)
   11. "And if you should count the favor of Allah, you could not enumerate it." (14:34)
   12. "Indeed, mankind is [generally] most unjust and ungrateful." (14:34)
   13. "Then eat of what Allah has provided for you [which is] lawful and good." (16:114)
   14. "And be grateful for the favor of Allah, if it is [indeed] Him that you worship." (16:114)
   15. "And He is the One who produced for you hearing and vision and hearts; little are you grateful." (23:78)
   16. "Say, 'It is He who has produced you and made for you hearing and vision and hearts; little are you grateful.'" (67:23)
   17. "And weave the night and the day as a succession for whoever desires to remember or desires gratitude." (25:62)
   18. "And Allah has brought you out from the wombs of your mothers not knowing a thing." (16:78)
   19. "And He made for you hearing and vision and intellect that perhaps you would be grateful." (16:78)
   20. "What would Allah do with your punishment if you are grateful and believe?" (4:147)
   21. "And ever is Allah Appreciative and Knowing." (4:147)
   22. "My Lord, enable me to be grateful for Your favor which You have bestowed upon me and upon my parents." (27:19)
   23. "And to do righteousness of which You approve." (27:19)
   24. "And admit me by Your mercy into [the ranks of] Your righteous servants." (27:19)
   25. "This is from the favor of my Lord to test me whether I will be grateful or ungrateful." (27:40)
   26. "And whoever is grateful - his gratitude is only for [the benefit of] himself." (27:40)
   27. "And whoever is ungrateful - then indeed, my Lord is Free of need and Generous." (27:40)
   28. "So eat from the provision of your Lord and be grateful to Him." (34:15)
   29. "A good land [you have], and a Forgiving Lord." (34:15)
   30. "And We have enjoined upon man [care] for his parents." (31:14)
   31. "His mother carried him, [increasing her] in weakness upon weakness." (31:14)
   32. "And his weaning is in two years." (31:14)

## July: Hope, Guidance, & Light (Hudah & Nur)

   1. "Allah is the Light of the heavens and the earth." (24:35)
   2. "The example of His light is like a niche within which is a lamp." (24:35)
   3. "The lamp is within glass, the glass as if it were a pearly [white] star." (24:35)
   4. "Lit from [the oil of] a blessed olive tree, neither of the east nor of the west." (24:35)
   5. "Whose oil would almost glow even if untouched by fire." (24:35)
   6. "Light upon light. Allah guides to His light whom He wills." (24:35)
   7. "And Allah presents examples for the people, and Allah is Knowing of all things." (24:35)
   8. "This is the Book about which there is no doubt, a guidance for those conscious of Allah." (2:2)
   9. "Who believe in the unseen, establish prayer, and spend out of what We have provided for them." (2:3)
   10. "And who believe in what has been revealed to you, [O Muhammad], and what was revealed before you." (2:4)
   11. "And of the Hereafter they are certain [in faith]." (2:4)
   12. "Those are upon [right] guidance from their Lord, and it is those who are the successful." (2:5)
   13. "And He is with you wherever you are." (57:4)
   14. "And Allah, of what you do, is Seeing." (57:4)
   15. "And We have already created man and know what his soul whispers to him." (50:16)
   16. "And We are closer to him than [his] jugular vein." (50:16)
   17. "Say, 'Indeed, the guidance of Allah is the [only] guidance.'" (2:120)
   18. "And We have sent down to you the Book as clarification for all things." (16:89)
   19. "And as guidance and mercy and good tidings for the Muslims." (16:89)
   20. "Can he who was dead and We gave him life and made for him light by which to walk among the people..." (6:122)
   21. "...be like one who is in darkness, from which he cannot come out?" (6:122)
   22. "Thus it has been made pleasing to the disbelievers that which they were doing." (6:122)
   23. "He brings them out of darkness into light by His permission." (5:16)
   24. "And guides them to a straight path." (5:16)
   25. "There has come to you from Allah a light and a clear Book." (5:15)
   26. "By which Allah guides those who pursue His pleasure into the ways of peace." (5:16)
   27. "A Book which We have revealed to you, [O Muhammad], that you might bring mankind out of darknesses into the light." (14:1)
   28. "By permission of their Lord to the path of the Exalted in Might, the Praiseworthy." (14:1)
   29. "Believe in Allah and His Messenger and the light which We have sent down." (64:8)
   30. "And Allah is Acquainted with what you do." (64:8)
   31. "O mankind, there has come to you a conclusive proof from your Lord." (4:174)
   32. "And We have sent down to you a clear light." (4:174)

## August: Justice, Honesty, & Fairness (Adl)

   1. "Indeed, Allah orders justice and good conduct and giving to relatives." (16:90)
   2. "And forbids immorality and bad conduct and oppression." (16:90)
   3. "He admonishes you that perhaps you will be reminded." (16:90)
   4. "O you who have believed, be persistently standing firm in justice, witnesses for Allah." (4:135)
   5. "Even if it be against yourselves or parents and relatives." (4:135)
   6. "Whether one is rich or poor, Allah is more worthy of both." (4:135)
   7. "So follow not [personal] inclination, lest you not be just." (4:135)
   8. "And if you distort [your testimony] or refuse [to give it], then indeed Allah is ever, with what you do, Acquainted." (4:135)
   9. "O you who have believed, be persistently standing firm for Allah, witnesses in justice." (5:8)
   10. "And do not let the hatred of a people prevent you from being just." (5:8)
   11. "Be just; that is nearer to righteousness." (5:8)
   12. "And fear Allah; indeed, Allah is Acquainted with what you do." (5:8)
   13. "And give full measure and weight in justice." (6:152)
   14. "We do not burden any soul except to its capacity." (6:152)
   15. "And when you testify, be just, even if it be [against] a near relative." (6:152)
   16. "And the covenant of Allah fulfill." (6:152)
   17. "This He has commanded you that you may be reminded." (6:152)
   18. "Woe to those who give less [than due]." (83:1)
   19. "Who, when they take a measure from people, take in full." (83:2)
   20. "But if they give by measure or by weight to them, they cause loss." (83:3)
   21. "Do they not think that they will be resurrected?" (83:4)
   22. "For a tremendous Day." (83:5)
   23. "The Day when mankind will stand before the Lord of the worlds?" (83:6)
   24. "And We place the scales of justice for the Day of Resurrection, so no soul will be treated unjustly at all." (21:47)
   25. "And if there is [even] the weight of a mustard seed, We will bring it forth." (21:47)
   26. "And sufficient are We as accountant." (21:47)
   27. "Indeed, Allah does not do injustice, [even] as much as an atom's weight." (4:40)
   28. "And if there is a good deed, He multiplies it and gives from Himself a great reward." (4:40)
   29. "And sky He raised and imposed the balance." (55:7)
   30. "That you not transgress within the balance." (55:8)
   31. "And establish weight in justice and do not make deficient the balance." (55:9)

## September: Kindness & Speech (Ihsan & Qawl)

   1. "And speak to people good [words]." (2:83)
   2. "And tell My servants to say that which is best." (17:53)
   3. "Indeed, Satan induces [dissension] among them." (17:53)
   4. "Indeed Satan is ever, to mankind, a clear enemy." (17:53)
   5. "A kind word and forgiveness are better than charity followed by injury." (2:263)
   6. "And Allah is Free of need and Forbearing." (2:263)
   7. "O you who have believed, fear Allah and speak words of appropriate justice." (33:70)
   8. "He will [then] amend for you your deeds and forgive you your sins." (33:71)
   9. "And whoever obeys Allah and His Messenger has certainly attained a great attainment." (33:71)
   10. "And not equal are the good deed and the bad." (41:34)
   11. "Repel [evil] by that [deed] which is better." (41:34)
   12. "And thereupon, the one whom between you and him is enmity [will become] as though he were a devoted friend." (41:34)
   13. "But none is granted it except those who are patient." (41:35)
   14. "And none is granted it except one having a great portion [of good]." (41:35)
   15. "And if an evil suggestion comes to you from Satan, then seek refuge in Allah." (41:36)
   16. "Indeed, He is the Hearing, the Knowing." (41:36)
   17. "And when the ignorant address them [harshly], they say [words of] peace." (25:63)
   18. "The servants of the Most Merciful are those who walk upon the earth easily." (25:63)
   19. "And walk moderately and lower your voice." (31:19)
   20. "Indeed, the most disagreeable of sounds is the voice of donkeys." (31:19)
   21. "Do you not see how Allah presents an example, a good word like a good tree?" (14:24)
   22. "Whose root is firmly fixed and its branches [high] in the sky?" (14:24)
   23. "It produces its fruit all the time, by permission of its Lord." (14:25)
   24. "And Allah presents examples for the people that perhaps they will be reminded." (14:25)
   25. "And the example of a bad word is like a bad tree, uprooted from the surface of the earth." (14:26)
   26. "It has no stability." (14:26)
   27. "Allah keeps firm those who believe, with the firm word, in worldly life and in the Hereafter." (14:27)
   28. "And Allah sends astray the wrongdoers. And Allah does what He wills." (14:27)
   29. "Is the reward for good [anything] but good?" (55:60)

## October: Charity & Good Deeds (Sadaqah)

   1. "Believe in Allah and His Messenger and spend out of that in which He has made you successors." (57:7)
   2. "For those of you who have believed and spent, there will be a great reward." (57:7)
   3. "The example of those who spend their wealth in the way of Allah is like a seed [of grain]." (2:261)
   4. "Which grows seven ears; in each ear is a hundred grains." (2:261)
   5. "And Allah multiplies [the reward] for whom He wills." (2:261)
   6. "And Allah is all-Encompassing and Knowing." (2:261)
   7. "Those who spend their wealth in the way of Allah and then do not follow up what they have spent with reminders [of it] or injury..." (2:262)
   8. "...will have their reward with their Lord, and there will be no fear concerning them, nor will they grieve." (2:262)
   9. "O you who have believed, spend from the good things which you have earned." (2:267)
   10. "And from that which We have produced for you from the earth." (2:267)
   11. "By no means shall you attain righteousness unless you give [freely] from that which you love." (3:92)
   12. "And whatever you spend - indeed, Allah is Knowing of it." (3:92)
   13. "If you disclose your charitable offerings, they are good." (2:271)
   14. "But if you conceal them and give them to the poor, it is better for you." (2:271)
   15. "And He will remove from you some of your misdeeds [thereby]." (2:271)
   16. "And Allah, with what you do, is Acquainted." (2:271)
   17. "Those who spend [in the cause of Allah] during ease and hardship." (3:134)
   18. "And who restrain anger and who pardon the people." (3:134)
   19. "And Allah loves the doers of good." (3:134)
   20. "And whatever you spend of good - it will be fully repaid to you, and you will not be wronged." (2:272)
   21. "Who establish prayer and spend from what We have provided them." (22:35)
   22. "And establish prayer and give zakah and loan Allah a goodly loan." (73:20)
   23. "And whatever good you put forward for yourselves - you will find it with Allah." (73:20)
   24. "It is better and greater in reward. And seek forgiveness of Allah." (73:20)
   25. "Indeed, Allah is Forgiving and Merciful." (73:20)
   26. "Righteousness is not that you turn your faces toward the east or the west." (2:177)
   27. "But [true] righteousness is [in] one who believes in Allah, the Last Day, the angels, the Book, and the prophets." (2:177)
   28. "And gives wealth, in spite of love for it, to relatives, orphans, the needy, the traveler, those who ask [for help], and for freeing slaves." (2:177)
   29. "[And who] establishes prayer and gives zakah; [those who] fulfill their promise when they promise." (2:177)
   30. "And [who] are patient in poverty and hardship and during battle." (2:177)
   31. "Those are the ones who have been true, and it is those who are the righteous." (2:177)

## November: Wisdom, Knowledge, & Reflection (Hikmah)

   1. "He gives wisdom to whom He wills." (2:269)
   2. "And whoever has been given wisdom has certainly been given much good." (2:269)
   3. "And none will remember except those of understanding." (2:269)
   4. "Then do they not reflect upon the Quran?" (4:82)
   5. "If it had been from [any] other than Allah, they would have found within it much contradiction." (4:82)
   6. "[This is] a blessed Book which We have revealed to you, [O Muhammad]." (38:29)
   7. "That they might reflect upon its verses and that those of understanding would be reminded." (38:29)
   8. "Say, 'Are those who know equal to those who do not know?'" (39:9)
   9. "Only they will remember [who are] people of understanding." (39:9)
   10. "Allah will raise those who have believed among you and those who were given knowledge, by degrees." (58:11)
   11. "And Allah is Acquainted with what you do." (58:11)
   12. "Indeed, in the creation of the heavens and the earth..." (3:190)
   13. "...and the alternation of the night and the day are signs for those of understanding." (3:190)
   14. "Who remember Allah while standing or sitting or [lying] on their sides." (3:191)
   15. "And give thought to the creation of the heavens and the earth, [saying]..." (3:191)
   16. "...'Our Lord, You did not create this aimlessly; exalted are You; then protect us from the punishment of the Fire.'" (3:191)
   17. "And We have certainly made the Quran easy for remembrance, so is there any who will remember?" (54:17)
   18. "Then do they not look at the camels - how they are created?" (88:17)
   19. "And at the sky - how it is raised?" (88:18)
   20. "And at the mountains - how they are erected?" (88:19)
   21. "And at the earth - how it is spread out?" (88:20)
   22. "So remind, [O Muhammad]; you are only a reminder." (88:21)
   23. "You are not over them a controller." (88:22)
   24. "And these examples We present to the people, but none will understand them except those of knowledge." (29:43)
   25. "He detailed the signs for a people who know." (10:5)
   26. "He details the signs for a people who think." (10:24)
   27. "Indeed in that are signs for a people who give thought." (13:3)
   28. "Indeed in that is a sign for a people who listen." (10:67)
   29. "Indeed in that are signs for a people who use reason." (13:4)

## December: Purpose, Evaluation, & The Hereafter (Akhirah)

   1. "And this worldly life is not but diversion and amusement." (29:64)
   2. "And indeed, the home of the Hereafter - that is the [true] life, if only they knew." (29:64)
   3. "Know that the life of this world is but amusement and diversion and adornment and boasting to one another." (57:20)
   4. "And competition in increase of wealth and children." (57:20)
   5. "Every soul will taste death, and you will only be given your [full] compensation on the Day of Resurrection." (3:185)
   6. "So he who is drawn away from the Fire and admitted to Paradise has attained [his desire]." (3:185)
   7. "And what is the life of this world except the enjoyment of delusion?" (3:185)
   8. "O you who have believed, fear Allah. And let every soul look to what it has put forth for tomorrow." (59:18)
   9. "And fear Allah; indeed, Allah is Acquainted with what you do." (59:18)
   10. "And be not like those who forgot Allah, so He made them forget themselves." (59:19)
   11. "Those are the defiantly disobedient." (59:19)
   12. "Did you think that We created you uselessly and that to Us you would not be returned?" (23:115)
   13. "So exalted be Allah, the Sovereign, the Truth; there is no deity except Him, Lord of the Noble Throne." (23:116)
   14. "Wealth and children are [but] adornment of the worldly life." (18:46)
   15. "But the enduring good deeds are better to your Lord for reward and better for [one's] hope." (18:46)
   16. "So whoever does an atom's weight of good will see it." (99:7)
   17. "And whoever does an atom's weight of evil will see it." (99:8)
   18. "To Him is your return all together." (10:4)
   19. "[The promise of] Allah is true." (10:4)
   20. "Indeed, He begins the creation and then repeats it that He may reward those who believed and did righteous deeds in justice." (10:4)
   21. "Race toward forgiveness from your Lord and a Garden whose width is like the width of the sky and the earth." (57:21)
   22. "Prepared for those who believed in Allah and His messengers." (57:21)
   23. "That is the bounty of Allah which He gives to whom He wills, and Allah is the possessor of great bounty." (57:21)
   24. "Whatever you have will end, but what Allah has is enduring." (16:96)
   25. "And We will surely give those who were patient their reward according to the best of what they used to do." (16:96)
   26. "The Day every soul will find what it has done of good present [before it]." (3:30)
   27. "And what it has done of evil, it will wish that between itself and that [evil] was a great distance." (3:30)
   28. "And Allah warns you of Himself, and Allah is Kind to [His] servants." (3:30)
   29. "But you prefer the worldly life." (87:16)
   30. "While the Hereafter is better and more enduring." (87:17)
   31. "Indeed, this is in the former scriptures, the scriptures of Abraham and Moses." (87:18-19)
`;

const lines = rawQuotes.split('\\n');
const quotes = [];
let idCounter = 1;

for (const line of lines) {
  const match = line.match(/^\\s*\\d+\\.\\s+"(.*)"\\s+\\((.*?)\\)/);
  if (match) {
    const text = match[1];
    let reference = match[2];
    
    // Some references are ranges like "87:18-19"
    // Extract surahId and ayah
    let surahId = null;
    let ayah = null;
    if (reference.includes(':')) {
      const parts = reference.split(':');
      surahId = parseInt(parts[0], 10);
      ayah = parts[1];
    }
    
    quotes.push({
      id: idCounter++,
      text: text,
      surahId: surahId,
      ayah: ayah
    });
  }
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

fs.writeFileSync(path.join(__dirname, 'src', 'data', 'quotes.json'), JSON.stringify(quotes, null, 2));

console.log('Generated quotes.json with ' + quotes.length + ' entries.');
